### ISSUE TITLE
File Not Existing?

### ISSUE THREAD

**Issue by Tricksta1999** [The-1-7-10-Pack/The-1.7.10-Pack#502]
Hi

When I try installing the Modpack it comes up with

Error unzipping a file for the following pack: The 1.7.10 Pack
Attempting to extract file the-1710-pack-0.7.6c.zip, but it did not exist.
Please consult the Modpack Author

**Comment by The-1-7-10-Pack** [comment]
Our solder API was offline, should work now. Sorry!

**Comment by Tricksta1999** [comment]
okay thanks :D keep up the good work you are doing

**Comment by Tricksta1999** [comment]
hi I replyed to the post on GitHub but when I tried installing it it still
did not work with the same message

**Comment by The-1-7-10-Pack** [comment]
@Tricksta1999 Huh? The solder API is up.

**Comment by Tricksta1999** [comment]
i know I saw but it still wasn't installing, I deleted the pack and copied
the code again but still the same thing

**Comment by The-1-7-10-Pack** [comment]
@Tricksta1999 Maybe you're installing wrong? or your launcher is bad? try to install other modpacks. It's working for me and you're the only one complaining, weird!

**Comment by Tricksta1999** [comment]
okay I will try reinstalling the pack
