### ISSUE TITLE
How to Install Cauldran

### ISSUE THREAD

**Issue by cowboyup1987** [The-1-7-10-Pack/The-1.7.10-Pack#650]
I would like to install Cauldran so I can use some plugins before I let people I dont know join my server. If possable can you make a video tutorial.   Thanks my friends and I love the Modpack.

**Comment by The-1-7-10-Pack** [comment]
Simply download the [Cauldron files](http://tcpr.ca/cauldron) that will match the Forge version (1408), then put it in the server folder, and name it just as the Forge jar (and delete the Forge jar). Then Launch!

**Comment by cowboyup1987** [comment]
it didnt work so i will list step by step what i have done...1st i clicked on the cauldron files that was in blue text in your reply to my question. i then downloaded the KCauldron-1.7.10-1408.95.zip (usa) and saved it to my desktop. Then i STOP the server. I then edited the LaunchServer with notepad++ the folowing line...java -server -Xmx%mem% -XX:PermSize=256M -Dfml.queryResult=confirm -jar forge-1.7.10-10.13.2.1352-1.7.10-universal.jar nogui   to this...java -server -Xmx%mem% -XX:PermSize=256M -Dfml.queryResult=confirm -jar forge.jar nogui....I then opened the winrar of the download and moved the KCauldron-1.7.10-1408.95-server.jar file to the folder where the server is located and renamed the file to...forge...I then deleted the forge-1.7.10-10.13.3.1408-1.7.10-universal and launched the server and in the cmd is says " OS 64 " and the press any key to continue...

**Comment by The-1-7-10-Pack** [comment]
> java -server -Xmx%mem% -XX:PermSize=256M -Dfml.queryResult=confirm -jar **forge-1.7.10-10.13.2.1352-1.7.10-universal.jar** nogui

You need to have the bolded text name as the KCauldron jar.

**Comment by cowboyup1987** [comment]
what you have in bold is what i changed to just...forge... and then renamed the KCauldron file to ...forge...

**Comment by cowboyup1987** [comment]
![cant launch](https://cloud.githubusercontent.com/assets/12808935/8098295/d5a1c4d8-0fb3-11e5-81d8-4fe9f70835d5.PNG)


I re did it and just changed the names like u had said and still nothing

**Comment by The-1-7-10-Pack** [comment]
You have ".jar.jar".

**Comment by cowboyup1987** [comment]
Amazing..total palm to face. I never cought that. Thank you for taking the time to answer me. Server is up and running and now its just time to find the right plugins. Thank you so much. 2 BIG THUMBS UP!

**Comment by cowboyup1987** [comment]
Ok last question..after installing cauldron, anytime you type something into chat you get kicked from the game...any ideas on why?

**Comment by The-1-7-10-Pack** [comment]
That's an issue reported already, and that's not the modpack's problem.
Try to update the pack to v0.7.8 and then download the latest Cauldron for it, it should fix it.

**Comment by cowboyup1987** [comment]
the server download is still 0.7.7b is that right?

**Comment by cowboyup1987** [comment]
ok... so i saw the server update to 0.7.8 and i also installed the cauldron 1448 version and everything loads great...but the same problem of being kicked for typing something into chat is still a problem. if u have any other leads or suggestions i would greatly appreciate it.. Thanks for all the help.

**Comment by The-1-7-10-Pack** [comment]
Try to report it there: https://prok.pw/gitlab/Prototik/KCauldron/issues
Also give them your error.

**Comment by cowboyup1987** [comment]
ok so i left a message for the cauldron guys and they sent back a message that basically says to build my own modpack, because your modpack uses mods that arent compatiable with cauldron. i'd much rather use yours, mainly b/c the modpack i built is fine and has most of the mods that you use but it is super laggy. The question I have is..in the discussion portion of your modpack there is a server called blackwoods beast or something like that that uses your modpack and still uses plugins. I dont exactly care for what their doing there which is why im doing my own. Do you have any sugestions on how i can run your modpack and still have plugins?

**Comment by cowboyup1987** [comment]
and if skyping is an option im good with that too.

**Comment by The-1-7-10-Pack** [comment]
@cowboyup1987 I know some mods in the pack are incompatible with Cauldron, so I guess you can easily remove them. One mod is ColorChat, try removing it and see if there's any change.

**Comment by cowboyup1987** [comment]
that was the one..it works..and if you ever want to join us..let me know..ill make you a V.I,P,
thanks

**Comment by The-1-7-10-Pack** [comment]
:+1:
